language: objective-c
os: osx
osx_image: xcode11.2
xcode_workspace: Chuck-Norris-facts.xcworkspace
xcode_scheme: Chuck-Norris-facts
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 8
notifications:
email:
  recipients:
    - j.batista.damasceno@icloud.com
  on_success: always # default: change
  on_failure: always # default: always
